### ISSUE TITLE
Integração com a TTN via API

### ISSUE THREAD

**Issue by renatopanda** [Hernani-Diniz/Final#2]
A aplicação web apresenta dados (temp. humidade, imagem) que são fornecidos por sensores ambientais espalhados por locais. Estes dados são recolhidos por sensores com LoRaWAN que utilizam a TTN para enviar os mesmos. Ou seja, a TTN serve de intermediário entre sensor e web app (sensor -> TTN <-> web app).

Logo há aqui alguns pontos importantes a ter em conta:
1. É necessário ter uma "aplicação" criada na TTN
2. É necessário adicionar à TTN cada dispositivo novo (sensor) que se pretenda utilizar, indicando o DEV EUID do mesmo (os TTN end devices)
3. Cada sensor terá que ter no seu código a lógica de recolha de dados e envio dos mesmos para a TTN, incluindo os valores de APP ID e APP KEY configurados (e reportará o seu DEV EUID)
4. A TTN terá que o payload formatting configurado, ou seja a transformação feita nos dados que chegam dos sensores, para que os mesmos sejam disponibilizados em JSON via MQTT (ou outra integração)
5. A web app interage com o network server da TTN para obter dos dados que chegam à "TTN app", a cada notificação vinda da TTN os dados são passados para a DB.

A versão atual da aplicação web consiste ainda num sistema de informação simples com alguns modelos (local, sensor, user, sensor_reading, outros?) e CRUD dos mesmos, vistas ligadas e questões de autorização/autenticação de users. Para que se torne um projeto útil falta a integração automática com a TTN, que consistirá em 4 tarefas possíveis (cada uma com seu issue separado):
- [x] Ao criar um novo sensor, este deve ser registado na TTN como end device via API - Hernani-Diniz/Final#1 
- [ ] Ao editar um sensor, caso seja necessário, a informação registada na TTN deve ser também alterada (alterações do dev euid permitidas? - Hernani-Diniz/Final#3
- [x] Ao apagar um sensor, este deve ser automaticamente removido da app na TTN - Hernani-Diniz/Final#4
- [x] Os dados ambientais vindos dos sensores que chegam à TTN devem ser passados para a web app (sensor readings, esquecer para já eventuais mensagens de erro/warning) - Hernani-Diniz/Final#5
- [ ] Os dados sobre imagens que chegam da TTN devem também ser comunicados para a web app Hernani-Diniz/Final#6
